image: alpine/edge
environment:
  PACKAGES: media-tv/plex-media-server
tasks:
- bootstrap: |
     cd overlay
     sudo .ci/bootstrap.sh ../prefix
- test: |
     cd overlay
     sudo .ci/test.sh ../prefix
- build: |
     cd overlay
     sudo .ci/build.sh ../prefix
