image: debian/stretch
packages:
  - curl
environment:
  PACKAGES: media-tv/plex-media-server
sources:
  - https://git.sr.ht/~fkmclane/overlay
tasks:
  - bootstrap: |
       cd overlay
       sudo --preserve-env=PACKAGES .ci/bootstrap.sh ../prefix
  - test: |
       cd overlay
       sudo --preserve-env=PACKAGES .ci/test.sh ../prefix
  - build: |
       cd overlay
       sudo --preserve-env=PACKAGES .ci/build.sh ../prefix
